### ISSUE TITLE
Text incorrectly deleted on Windows after Prettier runs

### ISSUE THREAD

**Issue by MikeMcC399** [bmish/eslint-doc-generator#725]
## Current behavior

On Windows:

If [Prettier](https://prettier.io/) is run on Markdown documents `docs/rules/*.md` it inserts a blank line underneath

```text
<!-- end auto-generated rule header -->
```

Prettier also converts the file from `CRLF` to `LF`.

If `eslint-doc-generator` is now run, then it deletes all text below the blank line and coverts the file back to `CRLF`.

## Expected behavior

`eslint-doc-generator` should preserve the text below the `auto-generated rule header` whether the file is using `CRLF` or `LF`.

## Steps to reproduce

Windows 11 24H2, Node.js `22.16.0` LTS
[eslint-doc-generator@2.1.2](https://github.com/bmish/eslint-doc-generator/releases/tag/v2.1.2)

```shell
git clone --branch test/windows https://github.com/MikeMcC399/eslint-plugin-cypress
cd eslint-plugin-cypress
npm ci
npx eslint-doc-generator
npx prettier --write docs/rules/no-assigning-return-values.md
npx eslint-doc-generator
git diff docs/rules/no-assigning-return-values.md
```

## Logs

```text
docs/rules/no-assigning-return-values.md 27ms
diff --git a/docs/rules/no-assigning-return-values.md b/docs/rules/no-assigning-return-values.md
index 2c3cf7d..df6e30b 100644
--- a/docs/rules/no-assigning-return-values.md
+++ b/docs/rules/no-assigning-return-values.md
@@ -3,6 +3,3 @@
 💼 This rule is enabled in the ✅ `recommended` config.

 <!-- end auto-generated rule header -->
-## Further Reading
-
-See [the Cypress Best Practices guide](https://on.cypress.io/best-practices#Assigning-Return-Values).
```

**Comment by MikeMcC399** [comment]
- This is an issue introduced in [1.7.1](https://github.com/bmish/eslint-doc-generator/releases/tag/v1.7.1) which included PR https://github.com/bmish/eslint-doc-generator/pull/524

**Comment by bmish** [comment]
Hmm, I thought that issue was fixed by:
- #590

**Comment by MikeMcC399** [comment]
@bmish 

> Hmm, I thought that issue was fixed by:
> 
> * [Respect EOL character from `.editorconfig` #590](https://github.com/bmish/eslint-doc-generator/pull/590)

The issue occurs with the latest version [eslint-doc-generator@2.1.2](https://github.com/bmish/eslint-doc-generator/releases/tag/v2.1.2)

I can work around it by running `unix2dos` after running Prettier, however `eslint-doc-generator` should not be causing destructive changes to Markdown files on Windows, even if the files are in `LF` format.

**Comment by Zamiell** [comment]
@MikeMcC399 Try again in v2.3.0.

**Comment by MikeMcC399** [comment]
@Zamiell 

> [@MikeMcC399](https://github.com/MikeMcC399) Can you try again in v2.3.0? I think the issue might be resolved now.

I updated the repro branch `test/windows` to [eslint-doc-generator@2.3.0](https://github.com/bmish/eslint-doc-generator/releases/tag/v2.3.0) and re-tested. The issue is not resolved. The valid text gets deleted.

If you have access to a Windows machine you can cross-check using the steps to reproduce in the original post.

**Comment by MikeMcC399** [comment]
Re-tested with 3.0.0
Issue continues

**Comment by MikeMcC399** [comment]
This issue is still reproducible on Windows 11 25H2 with `eslint-doc-generator@3.6.0`

**Comment by bmish** [comment]
@MikeMcC399 would you like to test this out? I have a potential fix in:
- https://github.com/eslint-community/eslint-doc-generator/pull/985

**Comment by MikeMcC399** [comment]
I updated the test branch and moved it to https://github.com/MikeMcC399/eslint-plugin-cypress/tree/725-test-windows-deletion

The repro steps on Windows are now:

```shell
git clone --branch 725-test-windows-deletion https://github.com/MikeMcC399/eslint-plugin-cypress
cd eslint-plugin-cypress
npm ci
npx eslint-doc-generator
npx prettier --write docs/rules/no-assigning-return-values.md
npx eslint-doc-generator
git diff docs/rules/no-assigning-return-values.md
```

The result of running with the released version eslint-doc-generator@3.6.0 is

```
$ npx eslint-doc-generator
npx prettier --write docs/rules/no-assigning-return-values.md
npx eslint-doc-generator
git diff docs/rules/no-assigning-return-values.md
`unsafe-to-chain-command` rule doc should have included one of these headers: Options, Config
`unsafe-to-chain-command` rule doc should have included one of these headers: Options, Config
warning: in the working copy of 'docs/rules/no-assigning-return-values.md', LF will be replaced by CRLF the next time Git touches it
diff --git a/docs/rules/no-assigning-return-values.md b/docs/rules/no-assigning-return-values.md
index e7593f6..0cff9a6 100644
--- a/docs/rules/no-assigning-return-values.md
+++ b/docs/rules/no-assigning-return-values.md
@@ -6,6 +6,12 @@

 <!-- end auto-generated rule header -->

+📝 Disallow assigning return values of `cy` calls.
+
+💼 This rule is enabled in the ✅ `recommended` config.
+
+<!-- end auto-generated rule header -->
+
 ## Further Reading

 See [the Cypress Best Practices guide](https://on.cypress.io/best-practices#Assigning-Return-Values).
```

**Comment by MikeMcC399** [comment]
@bmish 

> would you like to test this out? I have a potential fix in:
> 
> * [fix: process markdown using LF internally, applying each file's end of line only when writing #985](https://github.com/eslint-community/eslint-doc-generator/pull/985)

Thanks for your efforts to get rid of this long-running issue! I found that PR #985 would resolve it! 👍🏻 

---
Using instead https://github.com/eslint-community/eslint-doc-generator/pull/985 by running `npm pack` in the PR's branch and installing it globally, then running:

```shell
eslint-doc-generator
npx prettier --write docs/rules/no-assigning-return-values.md
eslint-doc-generator
git diff docs/rules/no-assigning-return-values.md
```

shows that this issue would be resolved by PR #985

**Comment by ankit1324** [comment]
I've opened #986 for this. Root cause: doc content is split into lines using the *configured* EOL, so an LF file with CRLF configured (the Windows-after-Prettier scenario here) becomes one giant "line" — the end-of-header marker is never found and everything below it gets deleted. The fix parses existing content EOL-agnostically while still writing output with the configured EOL, with regression tests for both mismatch directions.

**Comment by MikeMcC399** [comment]
@ankit1324 

I'm not sure why there would be a need for an alternate PR, when PR #985 from @bmish already appears to fix the issue. I am however not really into the depths of root cause and solution. I'm just impacted by the problem, so I don't want to say what the best approach is.

**Comment by ankit1324** [comment]
@MikeMcC399 You're completely right, and apologies for the noise — I should have checked the open PRs before jumping in with an alternate one. I hadn't spotted that @bmish already had #985 open, which is also the more thorough approach. I've closed #986 in favor of it. Sorry for the confusion, and thanks for the quick flag.

**Comment by bmish** [comment]
I've opened up a replacement fix:
- https://github.com/eslint-community/eslint-doc-generator/pull/987

I believe this will address both of @MikeMcC399's issues. 

Goal of this new PR is to adopt a more industry-standard approach:
- All markdown is parsed as LF internally
- Each file is written using: an explicit EditorConfig `end_of_line` for that file path, else **the end of line already predominant in that file**, else `os.EOL`. Your files keep their endings.
- Prettier config is no longer read for line endings. That inference (added later in #803) was actually harmful in your repo: `.prettierrc.json` exists but `**/*.md` is in your `.prettierignore`, so the tool assumed LF for markdown that Prettier never touches.

**Comment by MikeMcC399** [comment]
@bmish 

Thanks! I'll take a fresh look at the proposed fix at the beginning of next week.

The `.prettierignore` setting, which excludes Markdown, was just intended as a temporary measure because of the compatibility issues with the doc generator. It's still possible to use `prettier` manually against ignored files though.

Ultimately the goal would be to integrate `eslint-doc-generator` into CI for https://github.com/cypress-io/eslint-plugin-cypress which you had proposed through https://github.com/cypress-io/eslint-plugin-cypress/pull/115 in 2022! I picked that one up in 2024. This would allow the final step hopefully.

**Comment by MikeMcC399** [comment]
@bmish 

I checked the latest PR https://github.com/eslint-community/eslint-doc-generator/pull/987 and it solves this issue, but I'm still seeing #726 as unresolved.

I took a look at your line ending documentation and that prompted me to revisit the Prettier [End of Line](https://prettier.io/docs/options#end-of-line) documentation.

So I intend now to go ahead with:

1. Create [.gitattributes](https://git-scm.com/docs/gitattributes) with

    ```text
    * text=auto eol=lf
    ```

2. Create [.editorconfig](https://editorconfig.org/) with the following:

    ```text
    # See https://editorconfig.org
    root = true
    [*]
    end_of_line = lf
    insert_final_newline = true
    ```

If LF is used consistently, before `eslint-doc-generator` is executed, then everything works fine.

I'm not a formal maintainer of `eslint-plugin-cypress`, so I have to wait for the Cypress.io team to approve changes. I also took a break for a couple of months from this repo, and coming back there are several things that need cleaning up, so that may take a couple of days.

I'm happy to re-test for #726 without the above changes, for the general benefit of `eslint-doc-generator` users, however I think for the Cypress repo, setting up LF as default is the best solution.

**Comment by MikeMcC399** [comment]
The `master` (default) branch of the repo https://github.com/cypress-io/eslint-plugin-cypress has now been updated to use only `LF` end-of-line characters and the problem described in this issue no longer occurs in that repo's `master` branch.

It is however still reproducible in https://github.com/MikeMcC399/eslint-plugin-cypress/tree/725-test-windows-deletion using the released version of `eslint-doc-generator@3.6.0`

**Comment by bmish** [comment]
I'm hoping to merge and release #987 to start making progress on this as soon as I can get it reviewed.

**Comment by bmish** [comment]
@MikeMcC399 can you test out [v3.7.0](https://github.com/eslint-community/eslint-doc-generator/releases/tag/v3.7.0)?

**Comment by MikeMcC399** [comment]
@bmish 
> can you test out [v3.7.0](https://github.com/eslint-community/eslint-doc-generator/releases/tag/v3.7.0)?

Thanks for the new release! I can confirm that it resolves this issue! 🚀 
Congratulations on a major improvement in cross-platform interoperability robustness!

**Comment by bmish** [comment]
That's great news! Thanks for helping ensure we got this fixed.
